### ISSUE TITLE
yaml for all config options

### ISSUE THREAD

**Issue by mhulse** [mhulse/vagrant-latmp#78]
Need to figure out way to pass yaml to shell provisioner too.

**Comment by mhulse** [comment]
Can't use dot notation out of box when reading yaml.

https://stackoverflow.com/a/43006535/922323

Could convert to OpenStruct... Worth it?

Using `foo['blah']['baz']` etc. seems so cumbersome to me.

**Comment by mhulse** [comment]
So, I tried this:

```yml
vagrant:
  network:
    ip: "" # Blank for DHCP, or `192.168.x.x` for static IP.
    type: "public" # … or, 'private'.
  synced_folder:
    disabled: false # Windows users should set this to `true`.

php:
  enabled: true
  settings:
    version: "7.2" # Valid values: 5.6, 7.0, 7.1, 7.2
    memory_limit: "256"
    timezone: "America/Los_Angeles"
    max_execution_time: "60"

# nvm list-remote
node:
  enabled: true
  settings:
    version: "8"

git:
  enabled: true
  settings:
    config_name: ""
    config_email: ""

# rvm list known
ruby:
  enabled: true
  settings:
    version: "2.3.1"
```

And then in my `Vagrantfile`:

```ruby
# Load dependencies:
require 'yaml'

# Read configuration file:
options = YAML.load_file(
  File.join(
    File.dirname(__FILE__),
    'options.yaml'
  )
)
options = options.to_json
options = JSON.parse(options, {
    object_class: OpenStruct
})
```

From there I could do things like:

```ruby
options.vagrant.network.type
```

But in end, I felt like this overly complicated the setup.

Additionally, I could not think of an elegant way to pass yaml/json to shell provisioner.

In end, I think it makes more sense to follow KISS and put vars at top of `Vagrantfile` and `bootstrap/init.sh`.

Easy for someone to edit these vars ... Sooooo, why make things more complicated than it needs to be?
